from enum import Enum


class ConsentStatus(str, Enum):
    GRANTED = "GRANTED"
    REVOKED = "REVOKED"
    MODIFIED = "MODIFIED"
    PENDING = "PENDING"
    EXPIRED = "EXPIRED"


class ConsentPurpose(str, Enum):
    MARKETING = "MARKETING"
    ANALYTICS = "ANALYTICS"
    SERVICE_DELIVERY = "SERVICE_DELIVERY"
    THIRD_PARTY_SHARING = "THIRD_PARTY_SHARING"
    RESEARCH = "RESEARCH"
    COMPLIANCE = "COMPLIANCE"
    PAYMENT_PROCESSING = "PAYMENT_PROCESSING"
    LEGAL_OBLIGATION = "LEGAL_OBLIGATION"
    SECURITY = "SECURITY"


class DataType(str, Enum):
    PERSONAL_INFO = "PERSONAL_INFO"
    CONTACT_INFO = "CONTACT_INFO"
    FINANCIAL_DATA = "FINANCIAL_DATA"
    HEALTH_DATA = "HEALTH_DATA"
    LOCATION_DATA = "LOCATION_DATA"
    BEHAVIORAL_DATA = "BEHAVIORAL_DATA"
    BIOMETRIC_DATA = "BIOMETRIC_DATA"
    SENSITIVE_DATA = "SENSITIVE_DATA"
    GOVERNMENT_ID = "GOVERNMENT_ID"
    EDUCATION_DATA = "EDUCATION_DATA"
    EMPLOYMENT_DATA = "EMPLOYMENT_DATA"


class EventType(str, Enum):
    CONSENT_GRANTED = "CONSENT_GRANTED"
    CONSENT_REVOKED = "CONSENT_REVOKED"
    CONSENT_MODIFIED = "CONSENT_MODIFIED"
    DATA_ACCESS = "DATA_ACCESS"
    DATA_DELETION = "DATA_DELETION"
    CONSENT_EXPIRY = "CONSENT_EXPIRY"
    CONSENT_CREATED = "CONSENT_CREATED"
    CONSENT_RENEWED = "CONSENT_RENEWED"


class WebhookEvent(str, Enum):
    CONSENT_GRANTED = "consent.granted"
    CONSENT_REVOKED = "consent.revoked"
    CONSENT_MODIFIED = "consent.modified"
    CONSENT_EXPIRED = "consent.expired"
    CONSENT_CREATED = "consent.created"
    CONSENT_EXPIRING = "consent.expiring"
    DATA_DELETION = "data.deletion"
    BREACH_NOTIFICATION = "breach.notification"
    GRIEVANCE_CREATED = "grievance.created"
    GRIEVANCE_RESOLVED = "grievance.resolved"


class GrievanceType(str, Enum):
    UNAUTHORIZED_PROCESSING = "UNAUTHORIZED_PROCESSING"
    CONSENT_VIOLATION = "CONSENT_VIOLATION"
    DATA_BREACH = "DATA_BREACH"
    DELETION_FAILURE = "DELETION_FAILURE"
    PORTABILITY_ISSUE = "PORTABILITY_ISSUE"
    ACCESS_DENIED = "ACCESS_DENIED"
    CORRECTION_DENIED = "CORRECTION_DENIED"
    OTHER = "OTHER"


class GrievanceStatus(str, Enum):
    PENDING = "PENDING"
    ACKNOWLEDGED = "ACKNOWLEDGED"
    INVESTIGATING = "INVESTIGATING"
    RESOLVED = "RESOLVED"
    ESCALATED = "ESCALATED"
    REJECTED = "REJECTED"


class GrievancePriority(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class GuardianType(str, Enum):
    PARENT = "PARENT"
    LEGAL_GUARDIAN = "LEGAL_GUARDIAN"
    COURT_APPOINTED = "COURT_APPOINTED"
    POWER_OF_ATTORNEY = "POWER_OF_ATTORNEY"
    NOMINATED_REPRESENTATIVE = "NOMINATED_REPRESENTATIVE"


class GuardianStatus(str, Enum):
    PENDING = "PENDING"
    ACTIVE = "ACTIVE"
    SUSPENDED = "SUSPENDED"
    REVOKED = "REVOKED"


class PrincipalCategory(str, Enum):
    MINOR = "MINOR"
    PERSON_WITH_DISABILITY = "PERSON_WITH_DISABILITY"
    INCAPACITATED = "INCAPACITATED"
    GENERAL = "GENERAL"


class BreachSeverity(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class BreachStatus(str, Enum):
    DETECTED = "DETECTED"
    INVESTIGATING = "INVESTIGATING"
    CONTAINED = "CONTAINED"
    NOTIFIED = "NOTIFIED"
    RESOLVED = "RESOLVED"


class BreachType(str, Enum):
    UNAUTHORIZED_ACCESS = "UNAUTHORIZED_ACCESS"
    DATA_LEAK = "DATA_LEAK"
    CYBER_ATTACK = "CYBER_ATTACK"
    INSIDER_THREAT = "INSIDER_THREAT"
    PHYSICAL_THEFT = "PHYSICAL_THEFT"
    ACCIDENTAL_DISCLOSURE = "ACCIDENTAL_DISCLOSURE"
    SYSTEM_VULNERABILITY = "SYSTEM_VULNERABILITY"


class DeletionRequestStatus(str, Enum):
    PENDING = "PENDING"
    VERIFICATION_IN_PROGRESS = "VERIFICATION_IN_PROGRESS"
    SCHEDULED = "SCHEDULED"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    REJECTED = "REJECTED"


class DeletionScope(str, Enum):
    FULL = "FULL"
    PARTIAL = "PARTIAL"
    SPECIFIC_CONSENT = "SPECIFIC_CONSENT"


class RetentionException(str, Enum):
    LEGAL_OBLIGATION = "LEGAL_OBLIGATION"
    ONGOING_INVESTIGATION = "ONGOING_INVESTIGATION"
    CONTRACTUAL_REQUIREMENT = "CONTRACTUAL_REQUIREMENT"
    REGULATORY_COMPLIANCE = "REGULATORY_COMPLIANCE"


class ExportFormat(str, Enum):
    JSON = "JSON"
    CSV = "CSV"
    XML = "XML"
    PDF = "PDF"


class TransferStatus(str, Enum):
    PENDING = "PENDING"
    PROCESSING = "PROCESSING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class NotificationType(str, Enum):
    CONSENT_GRANTED = "CONSENT_GRANTED"
    CONSENT_EXPIRING = "CONSENT_EXPIRING"
    CONSENT_EXPIRED = "CONSENT_EXPIRED"
    CONSENT_REVOKED = "CONSENT_REVOKED"
    CONSENT_MODIFIED = "CONSENT_MODIFIED"
    GRIEVANCE_SUBMITTED = "GRIEVANCE_SUBMITTED"
    GRIEVANCE_ACKNOWLEDGED = "GRIEVANCE_ACKNOWLEDGED"
    GRIEVANCE_RESOLVED = "GRIEVANCE_RESOLVED"
    DELETION_REQUESTED = "DELETION_REQUESTED"
    DELETION_COMPLETED = "DELETION_COMPLETED"
    BREACH_NOTIFICATION = "BREACH_NOTIFICATION"
    GUARDIAN_REGISTERED = "GUARDIAN_REGISTERED"
    GUARDIAN_VERIFIED = "GUARDIAN_VERIFIED"
    SYSTEM_ANNOUNCEMENT = "SYSTEM_ANNOUNCEMENT"


class WebhookStatus(str, Enum):
    ACTIVE = "ACTIVE"
    PAUSED = "PAUSED"
    DISABLED = "DISABLED"


class TemplateLanguage(str, Enum):
    ENGLISH = "en"
    HINDI = "hi"
    TAMIL = "ta"
    TELUGU = "te"
    BENGALI = "bn"
    MARATHI = "mr"
    GUJARATI = "gu"
    KANNADA = "kn"
    MALAYALAM = "ml"
    PUNJABI = "pa"


class TemplateCategory(str, Enum):
    CONSENT_REQUEST = "CONSENT_REQUEST"
    CONSENT_GRANTED = "CONSENT_GRANTED"
    CONSENT_REVOKED = "CONSENT_REVOKED"
    CONSENT_EXPIRING = "CONSENT_EXPIRING"
    DATA_ACCESS = "DATA_ACCESS"
    DATA_DELETION = "DATA_DELETION"
    BREACH_NOTIFICATION = "BREACH_NOTIFICATION"
    GRIEVANCE = "GRIEVANCE"


class AuditRequestStatus(str, Enum):
    PENDING = "PENDING"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class AuditRequestType(str, Enum):
    ROUTINE = "ROUTINE"
    COMPLAINT_BASED = "COMPLAINT_BASED"
    RANDOM = "RANDOM"
    SPECIAL = "SPECIAL"
