CONSENT_GRANTED = "GRANTED"
CONSENT_REVOKED = "REVOKED"
CONSENT_MODIFIED = "MODIFIED"
CONSENT_PENDING = "PENDING"
CONSENT_EXPIRED = "EXPIRED"

PURPOSE_MARKETING = "MARKETING"
PURPOSE_ANALYTICS = "ANALYTICS"
PURPOSE_SERVICE_DELIVERY = "SERVICE_DELIVERY"
PURPOSE_THIRD_PARTY_SHARING = "THIRD_PARTY_SHARING"
PURPOSE_RESEARCH = "RESEARCH"
PURPOSE_COMPLIANCE = "COMPLIANCE"
PURPOSE_PAYMENT_PROCESSING = "PAYMENT_PROCESSING"

DATA_TYPES = {
    "PERSONAL_INFO": "Personal identification information",
    "CONTACT_INFO": "Contact details (email, phone, address)",
    "FINANCIAL_DATA": "Financial and transaction data",
    "HEALTH_DATA": "Health and medical records",
    "LOCATION_DATA": "Geolocation and movement data",
    "BEHAVIORAL_DATA": "Usage patterns and behavioral analytics",
    "BIOMETRIC_DATA": "Biometric identifiers",
    "SENSITIVE_DATA": "Sensitive personal data under DPDP Act",
}

DPDP_SENSITIVE_DATA_CATEGORIES = [
    "FINANCIAL_DATA",
    "HEALTH_DATA",
    "BIOMETRIC_DATA",
    "SEXUAL_ORIENTATION",
    "CASTE_OR_TRIBE",
    "RELIGIOUS_BELIEFS",
    "POLITICAL_OPINIONS",
    "GENETIC_DATA",
]

EVENT_TYPE_CONSENT_GRANTED = "CONSENT_GRANTED"
EVENT_TYPE_CONSENT_REVOKED = "CONSENT_REVOKED"
EVENT_TYPE_CONSENT_MODIFIED = "CONSENT_MODIFIED"
EVENT_TYPE_DATA_ACCESS = "DATA_ACCESS"
EVENT_TYPE_DATA_DELETION = "DATA_DELETION"
EVENT_TYPE_CONSENT_EXPIRY = "CONSENT_EXPIRY"

MAX_CONSENT_DURATION_DAYS = 365
MIN_CONSENT_DURATION_DAYS = 1
